### ISSUE TITLE
Syntax error 

### ISSUE THREAD

**Issue by osos** [rany2/grott#44]
Hi,

Just build the repo using the dockerfile.

While starting I get this error:

```
grott  | 2023-07-13T16:53:34.931976237Z Traceback (most recent call last):
grott  | 2023-07-13T16:53:34.932027234Z   File "grott.py", line 18, in <module>
grott  | 2023-07-13T16:53:34.932130687Z     from grottconf import Conf
grott  | 2023-07-13T16:53:34.932154148Z   File "/app/grottconf.py", line 44
grott  | 2023-07-13T16:53:34.932163761Z     if environ_value := get_option_environ(
grott  | 2023-07-13T16:53:34.932215476Z                       ^
grott  | 2023-07-13T16:53:34.932242216Z SyntaxError: invalid syntax
grott  | 2023-07-13T16:53:37.767804539Z Traceback (most recent call last):
grott  | 2023-07-13T16:53:37.768345709Z   File "grott.py", line 18, in <module>
grott  | 2023-07-13T16:53:37.768358510Z     from grottconf import Conf
grott  | 2023-07-13T16:53:37.768362346Z   File "/app/grottconf.py", line 44
grott  | 2023-07-13T16:53:37.768365742Z     if environ_value := get_option_environ(
grott  | 2023-07-13T16:53:37.768369035Z                       ^
grott  | 2023-07-13T16:53:37.768372249Z SyntaxError: invalid syntax
```

**Comment by rany2** [comment]
Can you try now?

**Comment by osos** [comment]
Better, but:

```
grott  | 2023-07-13T17:13:14.702621947Z Traceback (most recent call last):
grott  | 2023-07-13T17:13:14.702655347Z   File "/app/grott.py", line 20, in <module>
grott  | 2023-07-13T17:13:14.702659697Z     from grottproxy import Proxy
grott  | 2023-07-13T17:13:14.702662671Z   File "/app/grottproxy.py", line 12, in <module>
grott  | 2023-07-13T17:13:14.702691048Z     import libscrc
grott  | 2023-07-13T17:13:14.702701748Z ModuleNotFoundError: No module named 'libscrc'
grott  | 2023-07-13T17:13:17.572659641Z Traceback (most recent call last):
grott  | 2023-07-13T17:13:17.572687518Z   File "/app/grott.py", line 20, in <module>
grott  | 2023-07-13T17:13:17.572694717Z     from grottproxy import Proxy
grott  | 2023-07-13T17:13:17.572698199Z   File "/app/grottproxy.py", line 12, in <module>
grott  | 2023-07-13T17:13:17.572789842Z     import libscrc
grott  | 2023-07-13T17:13:17.572796613Z ModuleNotFoundError: No module named 'libscrc'
```

**Comment by osos** [comment]
Added:
```
COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt
```

and switched to python 3.8 fixed it



Switching to python 3.8

**Comment by rany2** [comment]
Hi yes, I fixed this later. Could you please test in latest master; I don't use docker at all

**Comment by rany2** [comment]
> Hi yes, I fixed this later. Could you please test in latest master; I don't use docker at all

FYI the files got renamed, so do an ls to figure out which docker image you want

**Comment by osos** [comment]
Seems to fail to compile libscrc with python 3.11-slim, but works with 3.8-slim

**Comment by rany2** [comment]
Thanks for info, downgraded to 3.8 for dockerfiles

**Comment by osos** [comment]
also need this it seems:
`COPY static /app/static`

**Comment by rany2** [comment]
thanks, I added that also

**Comment by rany2** [comment]
@osos P.S. I'm now daily driving the docker image and I improved it quite a lot, if you want a docker image that is fairly light try `ghcr.io/rany2/grott:master` as an image.
