### ISSUE TITLE
configparser error

### ISSUE THREAD

**Issue by hugoboss00** [rany2/grott#8]
Hi,
I have installed grott on a Raspberry (Buster) and also having installed python 3.8.12
But when starting grott i get this error:

Grott process configuration file
Traceback (most recent call last):
  File "grott.py", line 59, in <module>
    main()
  File "grott.py", line 29, in main
    conf = Conf(VERREL)
  File "/home/pi/grott/grottconf.py", line 157, in __init__
    self.procconf()
  File "/home/pi/grott/grottconf.py", line 414, in procconf
    self.mqttauth = config.getboolean(
TypeError: getboolean() takes 3 positional arguments but 4 were given

**Comment by hugoboss00** [comment]
wow, that was fast!
yes its fixed,
thanks
